### ISSUE TITLE
Kit Autosave enabled even if mission is not initialized

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#103]
Kit Autosave currently is active even if the mission does not have kit autosave enabled.
Instead, kit autosave should only be active when the current mission is initialized by the SIA3f framework.

There may be issues when on other servers or scenarios that don't use the framework with the framework loaded on the client.

**Comment by SiegeToaster** [comment]
Check [this](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/blob/main/addons%2Face%2Ffunctions%2Ffnc_updateAutosave.sqf#L19)
Try setting the default value to false, otherwise check for initialization.

Nice catch
