### ISSUE TITLE
Port TPD Teleport

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#16]
Port the TPD teleport scripts, functions, and GUI.  Also rename the function called in [core\XEH_serverPostInit](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/blob/main/addons/core/XEH_serverPostInit.sqf#L24-L32) to the proper name.

- [x] create GUIs & related configs
- [x] put ``ctrlStaticTitle``, ``ctrlStaticBackground``, ``ctrlListBox``, and ``ctrlButton`` into guiDefines.hpp
- [ ] find proper text values for localized text (e.g, TPD >> TPD_Teleport >> Headline >> text)
- [x] create teleport function

**Comment by L-McKendrick** [comment]
Is there a reason for replacing the localized text values? I'd think having it multi-lingual would be a positive, no?

**Comment by SiegeToaster** [comment]
> Is there a reason for replacing the localized text values? I'd think having it multi-lingual would be a positive, no?
> 
> Regardless, finished task 3 in [this commit.](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/commit/258641d50a2239c1c68bf76a668233e127c77c4d)

Stringtables are hard; we can make it an enhancement issue but I'm pretty sure everyone in the group needs to be at least good enough with English to communicate.
