### ISSUE TITLE
onPlayerKilled and onPlayerRespawn ports

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#17]
Use the [Killed](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Killed) and [Respawn](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Killed) event handlers.  Use the local version, NOT MPKilled/MPRespawn. 
 Additionally, use the parameter ``_unit`` instead of ``player`` to reference the player.

The variables set in ``onPlayerKilled`` do not necessarily need to be set to the player.  For example, line 1 of ``onPlayerKilled`` of the framework could be replaced with ``GVAR(mpttRadioList) = [] call acre_api_fnc_getMultiPushToTalkAssignment;`` as long as you do not run ``publicVariable`` on that gvar.

**Comment by L-McKendrick** [comment]
I'm not sure where exactly the event handlers should go and kinda on a time crunch so gonna just put the code here.

"Killed" code
`params ["_unit", "_killer", "_instigator", "_useEffects"];

GVAR(mpttRadioList) = [] call acre_api_fnc_getMultiPushToTalkAssignment;

GVAR(deathLoadout) = getUnitLoadout _unit;

GVAR(lastGroup) = group _unit;

GVAR(hadEarplugsIn) = [_unit] call ace_hearing_fnc_hasEarPlugsIn; 

[_unit, 4] call ace_medical_treatment_fnc_setTriageStatus // Set player's corpse triage to "Deceased"`

"Respawn" code

`params ["_unit", "_corpse"];

// Load saved _unit loadout
private _loadout = GVAR(savedLoadout);

// If _unit does not have a saved loadout, load loadout from death
if (isNil "_loadout") then {
	_unit setUnitLoadout GVAR(deathLoadout);
	hint "Gear from previous death loaded."
} else {
	_unit setUnitLoadout (savedLoadout);
	hint "Saved kit loaded.";
};

// Check if _unit had earplugs in on death, and put them back in.
if (GVAR(hadEarplugsIn)) then {
	_unit removeItem "ACE_EarPlugs";
	_unit addItem "ACE_EarPlugs";
	[_unit, true] call ace_hearing_fnc_putInEarplugs;
};

// Failsafe add _unit to old group
private _grp = GVAR(lastGroup);
if (group _unit != _grp) then { _unit joinSilent _grp };

// Restore ACRE PTT Assignment
waitUntil { ([] call acre_api_fnc_isInitialized) };
["loadRadioDefaultSpatials", []] spawn sia_f_fnc_ACRERadioSetup;
["reorderRadioMPTT", [GVAR(personalRadio)]] spawn sia_f_fnc_ACRERadioSetup;

// Exit _unit from AFK if still set as AFK
/* I"M NOT SURE HOW THE AFK IS HANDLED YET SORRY
private _isAFK = _unit getVariable ["sia_isAFK",false];
if (_isAFK) then { [false] spawn sia_f_fnc_exitAFK };
*/`

**Comment by SiegeToaster** [comment]
Final todo before closing: set repawnOnStart = -1
