### ISSUE TITLE
ACRE - Setup radio channels based on squad and role

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#26]
- [x] Frontend: Group Attribute 3DEN Parameter Input
- [x] Backend: Function to apply radio channel (may not be needed?)
- [x] Backend: Apply radio channel on join.
- [x] Backend: Apply radio channel on arsenal close.

Needs to be done in client init and onPlayerRespawn.  I think that this is different from the PTT persistence we already have, but we'll need to test.

**Comment by L-McKendrick** [comment]
Concept implementation:

- Add a unit attribute for radio channel (dropdown menu with channels 1-9).
- Read in sia_f_personalRadio and set channel for that radio. ex: `{some code checking if unit has radio, if so:} _success = [QGVAR(personalRadio), _valueFromUnitAttributeChannel] call acre_api_fnc_setRadioChannel;`

**Comment by L-McKendrick** [comment]
- [ ] Frontend: Group Attribute 3DEN Parameter Input
- [ ] Backend: Apply radio channel on join.
- [ ] Backend: Apply radio channel on respawn.
- [ ] Backend: Apply radio channel on arsenal close.
