### ISSUE TITLE
Local arsenal implementation

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#30]
- [x] create role GUI
- [x] create role functionality
- [x] edit role GUI
- [x] edit role functionality
- [x] apply role settings on start function

**Comment by L-McKendrick** [comment]
So my initial idea for implementing this was to add a category to the SIA Framework Settings called "Role Configuration" or something. 

There, each role is listed along with a text box for a list of item class names to add to that role's local arsenal.

However, this doesn't make the local arsenal setup much easier other than having it in-game. This also doesn't allow for custom roles to be added.

I'm open to other ideas for this system to be implemented. Perhaps it can be a part of a unit's attributes.

**Comment by SiegeToaster** [comment]
My idea is similar but instead of just listing class names, we should have a new GUI that is similar to or a copy of the ACE arsenal inventory screen.  It's something players are probably familiar with and is easy to use.

For the actual roles, I think a custom GUI will be needed.  We should have a screen that lists all of the roles in a dropdown thing, and whenever a role is selected all of the options show up.  Here's an illustration of what I mean:

![roleThingExample](https://user-images.githubusercontent.com/81945479/183303925-e3f4806b-46cc-40ea-aaf1-7c0cf8a02996.png)
