### ISSUE TITLE
Export scoreboard

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#31]
Export scoreboard to the RPT log using one of the logging macros and/or [diag_log](https://community.bistudio.com/wiki/diag_log).  See [exportScoreboard.sqf](https://github.com/Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR/blob/main/sia_f/missionEnd/exportScoreboard.sqf).

**Comment by SiegeToaster** [comment]
Next step is to find proper var for ``sia_f_missionName`` and call func at end of mission.

**Comment by L-McKendrick** [comment]
> Next step is to find proper var for `sia_f_missionName` and call func at end of mission.

Should be possible with `getMissionConfigValue ["onLoadName", missionName]`
