### ISSUE TITLE
Test for visual on comments in game

### ISSUE THREAD

**Issue by Heart-SIA** [Soliders-in-Arms-Arma-3-Group/sia3f#33]
https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/blob/2542bd871923ca6174c77f3bc1e52b53a21660c4/addons/core/XEH_serverPostInit.sqf#L26-L38

May not show in game, need to test to make sure, use a COUT variant if needed

**Comment by SiegeToaster** [comment]
Do you mean line 34 won't show up or that the items might not get added?  Line 34 should be replaced with one of the [RPT logging macros](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/wiki/Development#33-rpt-logging-macros) anyways.

**Comment by SiegeToaster** [comment]
idk what this is talking about and there hasn't been any follow up.
