### ISSUE TITLE
Move radio\Cfg3DEN to configuration\Cfg3DEN

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#37]
Anything that is strictly related to the Eden Editor should be put into the configuration module, all of the other modules are functions used in-game or both in-game and eden.

**Comment by L-McKendrick** [comment]
Did we reach a conclusion on our discussion?

Whether to keep all eden configuration in one module (\configuration),
OR
Follow ACE "practices" and have the eden configuration self-contained in the radio module.

**Comment by SiegeToaster** [comment]
https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/issues/37#issuecomment-1207804169

it's still up to you, but (as I stated in our discussion), I'd prefer to have all of the Eden Stuff in its own module (\configuration) as laid out in the framework flow diagram.  In my opinion, this will make things neater.  In an attempt to rescue the lost modularity, consider including a "configuration\Cfg3DENRadio.hpp" (or some other name) file into the main configuration\Cfg3DEN file, if you choose this route ofc.

**Comment by L-McKendrick** [comment]
[#37 (comment)](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/issues/37#issuecomment-1207804169)

Rgr
Will table the discussion to post alpha release and go with current planned outline in the meantime.
