### ISSUE TITLE
Allow GM to customize roles that have handheld/manpack radios

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#4]
See \addons\acre\functions\fnc_giveRadios.sqf:23-24
Currently, the roles that have certain radios are pre-defined. Add a way to allow GMs to customize this.  Maybe through a unit-specific trait or custom GUI?

**Comment by L-McKendrick** [comment]
Kind of going along with [my idea](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/issues/30#issuecomment-1201850174) for #30, we could add another category or even section to the SIA Framework settings called "Role Config", where all the role names are listed and add a setting for each role, however, this would result in a ton of bloat.

Another idea could be just adding a section in unit attributes. However, this possibly offers less modularity than tying it to the role.

I think some reconsideration regarding the role system may be required before working on this and #30.

**Comment by SiegeToaster** [comment]
See https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/issues/30#issuecomment-1207453644

**Comment by SiegeToaster** [comment]
This will be done in #30
