### ISSUE TITLE
Safe Start player invincibility and safety on

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#43]
See ye ole mission framework [f_safeStart.sqf:29-58](https://github.com/Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR/blob/ff914a40aa3197e0da54be90c8e9a39def903c98/sia_f/safeStart/f_safeStart.sqf#L29-L58)

**Comment by L-McKendrick** [comment]
To do:
[ ] - Fix safety not renabling after being turned off.
[ ] - Safety being enabled before Zeus is initialized.

**Comment by SiegeToaster** [comment]
2fa01f3e8685e6435b90d75c6f4ce22c0c503d6f closes this
