### ISSUE TITLE
Replace usage of real_date extension with CBA_fnc_weekDay

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#56]
`[systemTime] call CBA_fnc_weekDay;` should return the current day of the week, eliminating the need to call the real date extension for the [OCAP2 export](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/blob/2fa01f3e8685e6435b90d75c6f4ce22c0c503d6f/addons/core/XEH_serverPostInit.sqf#L96-L100). 

See the functions viewer in order to find documentation on `CBA_fnc_weekDay;` if needed.

**Comment by SiegeToaster** [comment]
syntax should be
```sqf
private _date = [systemTime] call CBA_fnc_weekDay;
```
_date is now
> Day of the week (0: Sunday, 6: Saturday, -1: invalid) <NUMBER>

[CBA_fnc_weekDay.sqf](https://github.com/CBATeam/CBA_A3/pull/1533/files#diff-734581193e290cb831ce5d585869ab5eddb61e76d198ab308e5175566b509037)
