### ISSUE TITLE
Add 3den custom composition for mission template

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#61]
No more steam workshop, now direct from the mod!

This is a temporary fix until something like #1 can be implemented.

**Comment by L-McKendrick** [comment]
[Example](https://github.com/GdC-Framework/GdC_lib/blob/master/gdc_lib_compositions/config.cpp) via
https://community.bistudio.com/wiki/BIS_fnc_exportCfgGroups

Unless this works: https://community.bistudio.com/wiki/Eden_Editor:_Custom_Composition#Modding_Compositions ?

**Comment by SiegeToaster** [comment]
The thing I originally looked at for this was like the example, didn't see BIS_fnc_exportCfgGroups though.  May as well try out the seemingly simpler Custom Composition thing first though.

**Comment by L-McKendrick** [comment]
Neither support multiple sides by the looks of it. Back to the drawing board :(
