### ISSUE TITLE
Make.py automatically mount P:\ drive

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#62]
That's it.  This is the last straw that broke the camels back on the way to the milk store.  I'm SICK.  I'm completely sick and tired and sick of seeing this whenever I try to work on the mod.
![image](https://user-images.githubusercontent.com/81945479/192654655-55ff683f-de2d-4387-a453-fcfec3b56700.png)

So, I will (eventually) edit make.py so that it automatically mounts the P:\ drive.

**Comment by L-McKendrick** [comment]
incredibly based
