### ISSUE TITLE
Disable Arsenal on Respawn functionality

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/sia3f#68]
see [\configutation\FrameworkSettings\arsenalOptions.hpp:6](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/blob/main/addons/configuration/FrameworkSettings/arsenalOptions.hpp#L5-L11).   Intended to allow GMs to give the players a 1-time access to the arsenal.

- [x] keep track of whether players have died after mission start
- [x] disable arsenal if above is true
- [x] allow GM to allow players to overwrite without having to use console

**Comment by L-McKendrick** [comment]
Easily concept to implement would just `hideObjectGlobal` on missionStart for all config arsenals.

One exception though would be players that join after mission start. Could perhaps unhide the arsenal for them that then hide after respawning.

And/or add a Zeus action that toggles arsenal visibility globally. (Could be available regardless of framework setting)
