### ISSUE TITLE
Big ole bugs

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#79]
The following bugs need to be determined if they:

- Are reproducible (and if so, how?).
- Occur locally or only in dedicated multiplayer.
- Work for JIPs

- [x] safeStart safety
✔️ Local
✔️ Dedicated
❔ JIPs
Cause: core/functions/safeStartInit.sqf is only run on the server, but the code inside is expecting it to be run globally.

- [x] Start Mission zeus action
✔️ Local
✔️ Dedicated
➖ JIPs

- [x] Briefing
✔️ Local
✔️ Dedicated
❔ JIPs
Cause: _Unknown, further testing needed._

- [ ] Role Groups sometimes get reset randomly?
❔ Local
❔ Dedicated
❔ JIPs
Cause: _Unknown, further testing needed._

- [x] #80
❔ Local
❔ Dedicated
➖ JIPs

- [x] #85 
✔️ Local
✔️ Dedicated
✔️ JIPs
Cause: According to the [wiki](https://community.bistudio.com/wiki/Arma_3:_Respawn#Respawn_Types), only markers can designate respawn positions when using the "BASE" template.

- [x] local arsenal
✔️ Local
✔️ Dedicated
✔️ JIPs
Cause: `sia3f_configuration_arsenals` was not a public variable, nor was passed to the function.

- [x] Briefing support info
✔️ Local
✔️ Dedicated
✔️ JIPs
Cause: `EGVAR(configuration,supportObjects)` is not a public variable.

- [x] AFK invincibility
✔️ Local
❔ Dedicated
❔ JIPs
Cause: Players were never made invincible originally.

These can be made into separate issues depending on the complexity.

**Comment by SiegeToaster** [comment]
Updated to show new bugs and fixes
