### ISSUE TITLE
Item Attributes > ACE Arsenal setup incompatible with Role Editor setup

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/sia3f#95]
It seems like the role editor will overwrite the arsenal settings in item attributes in some instances.

Reproducibility needs to be tested further.

Could potentially be caused by the code [here](https://github.com/Soliders-in-Arms-Arma-3-Group/sia3f/blob/8f76ef5842cadc88d8cd457052cbbbf3b0e3a6e4/addons/core/functions/fnc_setupGlobalArsenal.sqf#L31) wiping the existing arsenal, depending on initialization order.

EDIT: 
Waiting on https://github.com/acemod/ACE3/issues/10491

**Comment by L-McKendrick** [comment]
Steps to repro:

1. Setup basic mission (new scenario, save, init framework)
2. Place a unit, give him custom role.
3. Place arsenal and add to global arsenal.
4. Open role editor and a add item different item to custom role.
5. Load in game and access arsenal. Only the item from step 4 will show.

**Comment by SiegeToaster** [comment]
Only present in mp, works fine in singleplayer.

**Comment by L-McKendrick** [comment]
Still present in local MP, same repro.
Furthermore, if the arsenal is not initialized in the editor (ie has no items whitelisted), no arsenal will be created regardless of role editor settings.

**Comment by Toytap** [comment]
A potential short-term fix for this would be to change the workshop composition to add to the Arsenal box of something like say a map. So that way there is always something considered whitelisted in the Arsenal box.

**Comment by SiegeToaster** [comment]
> Still present in local MP, same repro.

Also present in SP
